[project]
protostar-version = "0.9.1"
lib-path = "lib"
cairo-path = ["lib", "./lib/cairo_contracts/src"]

[contracts]
simple = ["src/simple.cairo"]
braavos = ["src/braavos.cairo"]
proxy = ["lib/cairo_contracts/src/openzeppelin/upgrades/presets/Proxy.cairo"]
